config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sessions => 'my_devise/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'search#index'
    end
    unauthenticated :user do
      root to: 'my_devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :tickets
  resources :search

  namespace :admin do

    root 'base#index'
    resources :wagons

    resources :trains do
      resources :wagons
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :users
    resources :tickets

    resources :coupe_wagons, :controller => "wagons", :type => "CoupeWagon"
    resources :plackart_wagons, :controller => "wagons", :type => "PlackartWagon"
    resources :sv_wagons, :controller => "wagons", :type => "SvWagons"
    resources :sit_wagons, :controller => "wagons", :type => "SitWagon"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_search_result, only: [:show]

  def index
  end

  def show
    @start_station = params[:station_first]["id"]
    @end_station = params[:station_last]["id"]
    unless user_signed_in?
      flash.now.notice ="Login before buying tickets"
    end

  end

  private

  def set_search_result
    @routes = Route.search(params[:station_first], params[:station_last])
  end

end

app/views/search/index.html.erb
<h1>Select stations</h1>
<div class="row">
  <%= form_tag search_path(1), method: :get do %>
      <div class="col-md-4">
        <%= collection_select(:station_first, :id, RailwayStation.all, :id, :title, {}, {class:'form-control'}) %>
      </div>
      <div class="col-md-4">
        <%= collection_select(:station_last, :id, RailwayStation.all, :id, :title, {}, {class:'form-control'}) %>
      </div>
      <div class="col-md-4">
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
            Search <i class="icon-repeat"></i>
        <% end %>
      </div>
  <% end %>
</div>

app/views/search/show.html.erb
<table>
  <thead>
  <tr>
    <th>Number:</th>
    <th>Tickets:</th>
    <th>Depature time:</th>
    <th>Arrival time:</th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
      <% a = route %>
      <% departure = route.get_station_departure(@start_station) %>
      <% arrival = route.get_station_arrival(@end_station) %>
      <% route.trains.each do |train| %>
          <tr>
            <td><%= train.number %></td>
            <% if user_signed_in? %>
                <% if current_user.admin? %>
                    <td><%= link_to 'Buy tickets', new_admin_ticket_path(train_id: train.id,
                                                                         start_station_id: @start_station,
                                                                         end_station_id: @end_station) %>
                    </td>
                <% else %>
                    <td><%= link_to 'Buy tickets', new_ticket_path(train_id: train.id,
                                                                   start_station_id: @start_station,
                                                                   end_station_id: @end_station) %>
                    </td>
                <% end %>
            <% else %>
                <td><%= link_to 'Buy tickets', new_user_session_path %>
                </td>
            <% end %>

            <td><%= departure %></td>
            <td><%= arrival %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>