config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sessions => 'my_devise/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'search#index'
    end
    unauthenticated :user do
      root to: 'my_devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :tickets
  resources :search

  namespace :admin do

    root 'base#index'
    resources :wagons

    resources :trains do
      resources :wagons
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :users
    resources :tickets

    resources :coupe_wagons, :controller => "wagons", :type => "CoupeWagon"
    resources :plackart_wagons, :controller => "wagons", :type => "PlackartWagon"
    resources :sv_wagons, :controller => "wagons", :type => "SvWagons"
    resources :sit_wagons, :controller => "wagons", :type => "SitWagon"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user
  belongs_to :start_station, class_name: 'RailwayStation'
  belongs_to :end_station, class_name: 'RailwayStation'
  before_save :set_user_name, on: :create

  after_create :send_new_ticket
  after_destroy :send_remove_ticket
  def route_name
    "#{start_station.title} - #{end_station.title}"
  end

  def set_user_name
    self.full_name =  self.user.name
  end

  def send_new_ticket
    TicketMailer.buy_ticket(self.user,self).deliver_now
  end

  def send_remove_ticket
    TicketMailer.remove_ticket(self.user, self).deliver_now
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save!
      redirect_to [:admin, @ticket], notice: 'Ticket created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to [:admin, @ticket], notice: 'Ticket changed'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  #Находит объект в бд
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:train_id, :user_id, :full_name, :start_station_id, :end_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user! #, only: [:create, :destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = current_user.tickets.all
  end

  def show
    current_user.tickets.find(@ticket.id)
  end

  def new
    @ticket = current_user.tickets.new
    @train_id = params[:train_id]
    @station_first = params[:start_station_id]
    @station_last = params[:end_station_id]
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :edit
    end
  end

  def destroy
    current_user.tickets.find(@ticket.id).destroy
    redirect_to tickets_path
  end

  private

  #Находит объект в бд
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :end_station_id, :full_name, :passport)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/_form.html.erb
<%= form_with(model: [:admin,ticket], local: true) do |form| %>
    <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= t('common.errors')%> </h2>
          <ul>
            <% ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :user %>
      <%= form.collection_select(:user_id, User.all, :id, :name) %>
    </div>

    <div class="field">
      <%= form.label :train %>
      <%= form.collection_select(:train_id, Train.all, :id, :number) %>
    </div>

    <div class="field">
      <%= form.label :start_station %>
      <%= form.collection_select(:start_station_id, RailwayStation.all, :id, :title) %>
    </div>

    <div class="field">
      <%= form.label :end_station %>
      <%= form.collection_select(:end_station_id, RailwayStation.all, :id, :title) %>
    </div>

    <div class="actions">
      <%= form.submit t('.submit', action: @ticket.new_record? ? 'Создать' : 'Изменить')%>
    </div>
<% end %>

app/views/admin/tickets/_ticket.html.erb
<tr>
  <td>Ticket number: <%= ticket.id %></td>
  <td>Start station: <%= RailwayStation.find(ticket.start_station_id).title %></td>
  <td>End station: <%= RailwayStation.find(ticket.end_station_id).title %></td>
  <td><%= link_to 'Show', admin_ticket_path(ticket)%></td>
  <td><%= link_to 'Edit', edit_polymorphic_path([:admin, ticket]) %></td>
  <td><%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'are you sure?' } %></td>
</tr>

app/views/admin/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', admin_tickets_path %>

app/views/admin/tickets/index.html.erb
<h1>All Tickets:</h1>

<table>
  <thead>
  <tr>
    <th>Ticket number</th>
    <th>Start station</th>
    <th>End station</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render partial: "ticket", collection: @tickets, as: :ticket %>
  </tbody>
</table>

app/views/admin/tickets/new.html.erb
<h1>Новый билет</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', new_search_path %>

app/views/admin/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket number:</strong>
  <%= @ticket.id %>
</p>

<p>
  <strong>Information(full name, passport and email):</strong>
  <%= @ticket.full_name %>
  <%= @ticket.passport %>
  <%= @ticket.user.email %>
</p>
<p>
  <strong>Start station:</strong>
  <%= @ticket.start_station.title %>
</p>

<p>
  <strong>End station:</strong>
  <%= @ticket.end_station.title %>
</p>