config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sessions => 'my_devise/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'search#index'
    end
    unauthenticated :user do
      root to: 'my_devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :tickets
  resources :search

  namespace :admin do

    root 'base#index'
    resources :wagons

    resources :trains do
      resources :wagons
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :users
    resources :tickets

    resources :coupe_wagons, :controller => "wagons", :type => "CoupeWagon"
    resources :plackart_wagons, :controller => "wagons", :type => "PlackartWagon"
    resources :sv_wagons, :controller => "wagons", :type => "SvWagons"
    resources :sit_wagons, :controller => "wagons", :type => "SitWagon"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  def index

  end

  protected

  def check_admin
    redirect_to root_path, alert: 'No permission' unless current_user.admin?
  end
end

app/views/admin/base/index.html.erb
<h1><%=t :admin_cp_title%></h1>
<ul class="list-group">
  <li> <%= link_to "Railway Stations", admin_railway_stations_path, class: 'list-group-item' %> </li>
  <li> <%= link_to "Routes", admin_routes_path, class: 'list-group-item'%> </li>
  <li> <%= link_to "Tickets", admin_tickets_path, class: 'list-group-item'%> </li>
  <li> <%= link_to "Trains", admin_trains_path, class: 'list-group-item'%> </li>
  <li> <%= link_to "Wagons", admin_wagons_path, class: 'list-group-item'%> </li>
  <li> <%= link_to "Users", admin_users_path, class: 'list-group-item' %>   </li>
</ul>