config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sessions => 'my_devise/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'search#index'
    end
    unauthenticated :user do
      root to: 'my_devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :tickets
  resources :search

  namespace :admin do

    root 'base#index'
    resources :wagons

    resources :trains do
      resources :wagons
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :users
    resources :tickets

    resources :coupe_wagons, :controller => "wagons", :type => "CoupeWagon"
    resources :plackart_wagons, :controller => "wagons", :type => "PlackartWagon"
    resources :sv_wagons, :controller => "wagons", :type => "SvWagons"
    resources :sit_wagons, :controller => "wagons", :type => "SitWagon"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord

  before_validation :set_station, on: :create

  belongs_to :route
  has_many :tickets
  belongs_to :current_station, class_name: 'RailwayStation'
  has_many :wagons

  def wagons_seats_count
    second_class_count = wagons.where(type: :PlackartWagon).count
    compartment_count = wagons.where(type: :CoupeWagon).count
    sit_count = wagons.where(type: :SitWagon).count
    {second: second_class_count, comp: compartment_count, sit: sit_count}
  end

  def select_seats(type, seats_type)
    self.wagons.where(type: type).sum(seats_type.to_sym)
  end

  private

  def set_station
    station_id = route.railway_stations_routes.minimum(:railway_station_id)
    self.current_station = RailwayStation.find(station_id)
  end

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)
    respond_to do |format|
      if @train.save
        format.html { redirect_to [:admin,@train], notice: 'Train was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to [:admin,@train], notice: 'Train was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_path, notice: 'Train was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_with(model: [:admin, train], local: true) do |form| %>
    <% if train.errors.any? %>
        <div id="error_explanation">
          <h2><%= t('common.errors') %> </h2>

          <ul>
            <% train.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :number %>
      <%= form.number_field :number, id: :train_number %>
    </div>

    <div class="field">
      <%= form.label :route, 'Route' %>
      <%= form.collection_select :route_id, Route.all, :id, :name %>
    </div>

    <div class="actions">
      <%= form.submit t('.submit', action: @train.new_record? ? 'Создать' : 'Изменить') %>
    </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', admin_train_path(train) %></td>
  <td><%= link_to 'Edit', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Destroy', admin_train_path(train), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', [:admin,@train] %> |
<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Trains</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trains.each do |train| %>
      <%= render train %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Route:</strong>
  <% if @train.route %>
      <%= @train.route.name %>
  <% else %>
      Not specified
  <% end %>
</p>

<p>
  <strong>Wagons:</strong>
  <% if @train.wagons.empty? %>
      No wagons yet
  <% else %>
    <ul>
      <li>Count of compartment wagons: <%= @train.wagons_seats_count[:comp] %>
        <ul>
          <li>Up seats: <%= @train.wagons.where(type: :CoupeWagon).sum(:up_seats) %></li>
          <li>Down seats: <%= @train.wagons.where(type: :CoupeWagon).sum(:down_seats) %></li>
        </ul>
      <li>Count of second-class wagons: <%= @train.wagons_seats_count[:second] %>
        <ul>
          <li>Up seats: <%= @train.wagons.where(type: :PlackartWagon).sum(:up_seats) %></li>
          <li>Down seats: <%= @train.wagons.where(type: :PlackartWagon).sum(:down_seats) %></li>
        </ul>
      <li>Count of Sit wagons: <%= @train.wagons_seats_count[:sit] %>
        <ul>
          <li>Sit seats: <%= @train.wagons.where(type: :SitWagon).sum(:sit_seats) %></li>
        </ul>
    </ul>
    <strong>Links to wagons:</strong>
    <% @train.wagons.order_from_head(@train).each do |wagon| %>
        <ul>
          <li>Wagon number: <%= link_to wagon.number, admin_train_wagon_path(@train.id) %></li>
        </ul>
    <% end %>
<% end %>
</p>

<p>
  <%= link_to "Add wagon", new_admin_train_wagon_path(@train) %>
</p>

<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_train_path %>